sudo: required

dist: trusty

language: node_js

node_js: '10.15.0'

cache:
  yarn: true
  directories:
    - 'node_modules'

before_install:
  - npm install -g yarn
install: yarn install --frozen-lockfile

jobs:
  include:
    # Run tests in parallel
    - stage: test
      script: yarn check:licenses
    - script: yarn check:security
    - script: yarn test:lint
    - script: yarn test:unit:ci
      # Upload coverage reports to Codecov
      after_success: yarn coverage-upload -t ${CODECOV_TOKEN}
    - stage: publish
      script: skip
      # Publish package to NPM
      deploy:
        provider: script
        skip_cleanup: true
        on:
          all_branches: true
        script: yarn release
      # Increase number of watchers
    - script: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      if: branch = master
      # Deploy Storybook to GitHub Pages
      before_deploy: yarn predeploy
      deploy:
        provider: script
        script: yarn deploy
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        on:
          branch: master
        local-dir: public
        target_branch: gh-pages
