sudo: required

dist: trusty

language: node_js

node_js: '10.15.0'

cache:
  yarn: true
  directories:
    - 'node_modules'

before_install:
  - npm install -g yarn
install: yarn install --frozen-lockfile

jobs:
  include:
    # Run tests in parallel
    - stage: test
      script: yarn check:security && yarn check:licenses
    - script: yarn test:lint-js
    - script: yarn test:unit --runInBand
      # Upload coverage reports to Codecov
      after_success: yarn coverage:upload -t ${CODECOV_TOKEN}
    - stage: publish
      script:
        # Increase number of watchers
        - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
        - yarn predeploy
      deploy:
        # Publish package to NPM
        - provider: script
          skip_cleanup: true
          script:
            - yarn release
        # Deploy docz and Storybook to GitHub Pages
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          on:
            branch: master
          local-dir: dist
          target_branch: gh-pages
