comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  require_base: no
  require_head: no
  branches: null
github_checks:
  annotations: false
ignore:
  - '**/index.*'
  - '**/*.stories.*'
