/**
 * This file is auto-generated from manifest.json by `npm run build`.
 * Do not edit it by hand, your changes will be overwritten.
 * To add or remove an entry, edit manifest.json instead.
 */

export const CARD_SCHEMES = [
  'alelo',
  'alternative_payment_method',
  'american_express',
  'apple_pay',
  'bancomat',
  'bancontact',
  'boleto',
  'card_unknown',
  'conecs',
  'diners_club',
  'discover',
  'eftpos',
  'elo',
  'elv',
  'girocard',
  'google_pay',
  'hipercard',
  'ideal',
  'interac',
  'jcb',
  'klarna',
  'maestro',
  'mastercard',
  'pay_pal',
  'pix',
  'pluxee',
  'sodexo',
  'sumup_card',
  'sumup_pay',
  'sumup_scheme',
  'swile',
  'ticket',
  'union_pay',
  'visa',
  'visa_electron',
  'vpay',
  'vr',
] as const;
