/**
 * This file is auto-generated from manifest.json by `npm run build`.
 * Do not edit it by hand, your changes will be overwritten.
 * To add or remove an entry, edit manifest.json instead.
 */

export const PAYMENT_METHODS = [
  'alelo',
  'american_express',
  'apple_pay',
  'banco_estado',
  'bancontact',
  'bitcoin',
  'blik',
  'boleto',
  'conecs',
  'dankort',
  'diners_club',
  'discover',
  'ec',
  'eftpos',
  'elo',
  'elv',
  'eps',
  'faster_payments',
  'girocard',
  'giropay',
  'google_pay',
  'hiper',
  'hipercard',
  'ideal',
  'interac',
  'iris',
  'jcb',
  'klarna',
  'maestro',
  'mastercard',
  'mybank',
  'nfc_payment',
  'pay_pal',
  'pix_full',
  'post_finance',
  'przelewy24',
  'red_compra',
  'samsung_pay',
  'satispay',
  'sepa',
  'sodexo',
  'sofort',
  'split',
  'swile',
  'ticket',
  'twint',
  'union_pay',
  'visa',
  'visa_electron',
  'vpay',
  'vr',
] as const;
