export const CREDIT_SCHEMES = {
  AMEX: 'amex',
  DINERS: 'diners',
  DISCOVER: 'discover',
  ELO: 'elo',
  JCB: 'jcb',
  MASTERCARD: 'mastercard',
  VISA: 'visa'
};

export const DEBIT_SCHEMES = {
  HIPERCARD: 'hipercard',
  MAESTRO: 'maestro'
};

export const SCHEMES = { ...CREDIT_SCHEMES, ...DEBIT_SCHEMES };

const SCHEMES_CL = [SCHEMES.MASTERCARD, SCHEMES.VISA];

const SCHEMES_BR = [
  SCHEMES.VISA,
  SCHEMES.MASTERCARD,
  SCHEMES.ELO,
  SCHEMES.HIPERCARD,
  SCHEMES.AMEX,
  SCHEMES.DISCOVER,
  SCHEMES.DINERS,
  SCHEMES.JCB
];

const SCHEMES_PL = [
  SCHEMES.MASTERCARD,
  SCHEMES.VISA,
  SCHEMES.AMEX,
  SCHEMES.JCB
];

const SCHEMES_SE = [
  SCHEMES.MASTERCARD,
  SCHEMES.VISA,
  SCHEMES.AMEX,
  SCHEMES.DISCOVER,
  SCHEMES.DINERS
];

const SCHEMES_DEFAULT = [
  SCHEMES.MASTERCARD,
  SCHEMES.VISA,
  SCHEMES.AMEX,
  SCHEMES.DISCOVER,
  SCHEMES.DINERS,
  SCHEMES.JCB
];

export const COUNTRY_SCHEMES = {
  BR: SCHEMES_BR,
  CL: SCHEMES_CL,
  PL: SCHEMES_PL,
  SE: SCHEMES_SE,
  default: SCHEMES_DEFAULT
};
