name: Github Actions

on:
  pull_request:
    paths:
      - '.github/**'

defaults:
  run:
    working-directory: ./.github

permissions:
  contents: read

jobs:
  actionlint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          sparse-checkout: |
            .github

      - uses: reviewdog/action-actionlint@v1.64.1
        with:
          filter_mode: nofilter
          fail_on_error: true
          reporter: github-pr-check
