name: Create SumUp React App

on:
  schedule:
    - cron: '0 3 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Bootstrap test app
        run: yarn create react-app test-app --template @sumup

      - name: Build test app
        run: cd test-app && yarn build
